version: 0.0
os: linux

# files:
#   - source: /index.html
#     destination: /var/www/html/

hooks:
  
  BeforeInstall:

    - location: dependency-install
      runas: root
      timeout: 300

    - runas: root
      location: start-nginx
      timeout: 300
      

  ApplicationStop:

    - runas: root
      location: stop-nginx
      timeout: 300
      
